[platformio]
default_envs = nano_esp32
src_dir = firmware/G3VescBridge

[env:nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=1

